# Generated by Django 3.2.2 on 2021-05-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='url_address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
